name: Test

on:
  push:
    branches:
      - development

jobs:
  test:
    strategy:
      matrix:
        nginx_version:
          - "1.21.6"
          - "mainline"
          - "1"
          - "1.21"
          - "latest"
          - "1.21.6-perl"
          - "mainline-perl"
          - "1-perl"
          - "1.21-perl"
          - "perl"
          - "1.21.6-alpine"
          - "mainline-alpine"
          - "1-alpine"
          - "1.21-alpine"
          - "alpine"
          - "1.21.6-alpine-perl"
          - "mainline-alpine-perl"
          - "1-alpine-perl"
          - "1.21-alpine-perl"
          - "alpine-perl"
          - "1.20.2"
          - "stable"
          - "1.20"
          - "1.20.2-perl"
          - "stable-perl"
          - "1.20-perl"
          - "1.20.2-alpine"
          - "stable-alpine"
          - "1.20-alpine"
          - "1.20.2-alpine-perl"
          - "stable-alpine-perl"
          - "1.20-alpine-perl"

    name: Test that the NGINX's Docker image is working properly
    runs-on: ubuntu-20.04

    steps:
      - name: Pull
        run: docker pull nginx:${{ matrix.nginx_version }}
      - name: Run
        run: docker run --detach --publish 80:80 --name nginx nginx:${{ matrix.nginx_version }}
      - name: HTTP Request
        run: curl http://localhost
      - name: Stop
        run: docker stop nginx
